apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akvprovider-demo
spec:
  provider: azure
  secretObjects:
  - secretName: democert-k8s
    type: kubernetes.io/tls
    data:
    - objectName: democert
      key: tls.key
    - objectName: democert
      key: tls.crt
  - secretName: demosecret-k8s
    type: Opaque
    data:
    - objectName: demosecret
      key: demosecret
  parameters:
    usePodIdentity: "false"
    keyvaultName: your-key-vault
    objects:  |
      array:
        - |
          objectName: demosecret
          objectType: secret
          objectVersion: ""
        - |
          objectName: democert
          objectType: cert
          objectVersion: ""
    tenantId: your-tenant-id
